
spring:
  cloud:
    gateway:
      #default-filters:
      #  - SessionAuth
      routes:
        - id: route1
          uri: http://10.89.3.47:8888
          filters:
          #  - StripPrefix=3
            - SessionAuth
          predicates:
            - Path=/api/**
        - id: route2
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/japi/**
  redis:
    database: 1
    host: 10.89.3.48
    password: Zaq12wsx@123!
server:
  port: 9090
